/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'
import { Route as DatasetsDatasetIdIndexRouteImport } from './routes/datasets/$datasetId/index'
import { Route as DatasetsDatasetIdReportRouteImport } from './routes/datasets/$datasetId/report'
import { Route as DatasetsDatasetIdReviewRouteImport } from './routes/datasets/$datasetId/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdIndexRoute = DatasetsDatasetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatasetsDatasetIdRoute,
} as any)
const DatasetsDatasetIdReportRoute = DatasetsDatasetIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DatasetsDatasetIdRoute,
} as any)
const DatasetsDatasetIdReviewRoute = DatasetsDatasetIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DatasetsDatasetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/$': typeof ApiSplatRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRouteWithChildren
  '/datasets/': typeof DatasetsIndexRoute
  '/datasets/$datasetId/report': typeof DatasetsDatasetIdReportRoute
  '/datasets/$datasetId/review': typeof DatasetsDatasetIdReviewRoute
  '/datasets/$datasetId/': typeof DatasetsDatasetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/$': typeof ApiSplatRoute
  '/datasets': typeof DatasetsIndexRoute
  '/datasets/$datasetId/report': typeof DatasetsDatasetIdReportRoute
  '/datasets/$datasetId/review': typeof DatasetsDatasetIdReviewRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/$': typeof ApiSplatRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRouteWithChildren
  '/datasets/': typeof DatasetsIndexRoute
  '/datasets/$datasetId/report': typeof DatasetsDatasetIdReportRoute
  '/datasets/$datasetId/review': typeof DatasetsDatasetIdReviewRoute
  '/datasets/$datasetId/': typeof DatasetsDatasetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/api/$'
    | '/datasets/$datasetId'
    | '/datasets/'
    | '/datasets/$datasetId/report'
    | '/datasets/$datasetId/review'
    | '/datasets/$datasetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/api/$'
    | '/datasets'
    | '/datasets/$datasetId/report'
    | '/datasets/$datasetId/review'
    | '/datasets/$datasetId'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/api/$'
    | '/datasets/$datasetId'
    | '/datasets/'
    | '/datasets/$datasetId/report'
    | '/datasets/$datasetId/review'
    | '/datasets/$datasetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRouteWithChildren
  DatasetsIndexRoute: typeof DatasetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId/': {
      id: '/datasets/$datasetId/'
      path: '/'
      fullPath: '/datasets/$datasetId/'
      preLoaderRoute: typeof DatasetsDatasetIdIndexRouteImport
      parentRoute: typeof DatasetsDatasetIdRoute
    }
    '/datasets/$datasetId/report': {
      id: '/datasets/$datasetId/report'
      path: '/report'
      fullPath: '/datasets/$datasetId/report'
      preLoaderRoute: typeof DatasetsDatasetIdReportRouteImport
      parentRoute: typeof DatasetsDatasetIdRoute
    }
    '/datasets/$datasetId/review': {
      id: '/datasets/$datasetId/review'
      path: '/review'
      fullPath: '/datasets/$datasetId/review'
      preLoaderRoute: typeof DatasetsDatasetIdReviewRouteImport
      parentRoute: typeof DatasetsDatasetIdRoute
    }
  }
}

interface DatasetsDatasetIdRouteChildren {
  DatasetsDatasetIdReportRoute: typeof DatasetsDatasetIdReportRoute
  DatasetsDatasetIdReviewRoute: typeof DatasetsDatasetIdReviewRoute
  DatasetsDatasetIdIndexRoute: typeof DatasetsDatasetIdIndexRoute
}

const DatasetsDatasetIdRouteChildren: DatasetsDatasetIdRouteChildren = {
  DatasetsDatasetIdReportRoute: DatasetsDatasetIdReportRoute,
  DatasetsDatasetIdReviewRoute: DatasetsDatasetIdReviewRoute,
  DatasetsDatasetIdIndexRoute: DatasetsDatasetIdIndexRoute,
}

const DatasetsDatasetIdRouteWithChildren =
  DatasetsDatasetIdRoute._addFileChildren(DatasetsDatasetIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  ApiSplatRoute: ApiSplatRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRouteWithChildren,
  DatasetsIndexRoute: DatasetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
